package Task1_b::Model::PhoneDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Task1_b::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:task1_b',
        user => 'root',
        password => 'root',
    }
);

=head1 NAME

Task1_b::Model::PhoneDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Task1_b>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Task1_b::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

tr0th

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
